UniqloMVC/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using UniqloMVC.DataAccess;
using UniqloMVC.ViewModels.Basket;

namespace UniqloMVC.ViewComponents
{
    public class HeaderViewComponent(UniqloDbContext _context) : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var basketIds = JsonSerializer.Deserialize<List<BasketProductItemVM>>(Request.Cookies["basket"] ?? "[]");
            var prods = await _context.Products.Where(x => basketIds.Select(y => y.Id).Any(y => y == x.Id))
                .Select(x=>new ProductItemVM
                {
                    Id = x.Id,
                    Discount = x.Discount,
                    ImageUrl=x.CoverImage,
                    Name = x.Name,
                    SellPrice = x.SellPrice,
                }).ToListAsync();

            foreach (var item in prods)
            {
                item.Count = basketIds!.FirstOrDefault(x=>x.Id == item.Id)!.Count;
            }

            return View(prods);
        }
    }
}

UniqloMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/favicon.ico">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <!-- Bootstrap Fremwork Main Css -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <!-- All Plugins css -->
    <link rel="stylesheet" href="~/assets/css/plugins.css">
    <!-- Theme shortcodes/elements style -->
    <link rel="stylesheet" href="~/assets/css/shortcode/shortcodes.css">
    <!-- Theme main style -->
    <link rel="stylesheet" href="~/assets/style.css">
    <!-- Responsive css -->
    <link rel="stylesheet" href="~/assets/css/responsive.css">
    <!-- User style -->
    <link rel="stylesheet" href="~/assets/css/custom.css">

    <!-- Modernizr JS -->
    <script src="~/assets/js/vendor/modernizr-3.11.2.min.js"></script>
</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Body main wrapper start -->
   
       @*  @await Component.InvokeAsync("Header")  *@
        <vc:header></vc:header>
        @RenderBody()
        <footer class="htc__foooter__area bg__cat--2 footer--4">
            <div class="container-fluid">
                <div class="footer__container clearfix">
                    <div class="row">
                        <!-- Start Single Footer Widget -->
                        <div class="col-md-6 col-lg-3 col-sm-6">
                            <div class="ft__widget">
                                <div class="ft__logo">
                                    <a href="index.html">
                                        <img src="~/assets/images/logo/uniqlo.png" alt="footer logo">
                                    </a>
                                </div>
                                <div class="footer__details">
                                    <p>Get 10% discount with notified about the latest news and updates.</p>
                                </div>
                            </div>
                        </div>
                        <!-- End Single Footer Widget -->
                        <!-- Start Single Footer Widget -->
                        <div class="col-md-6 col-lg-3 offset-lg-1 col-sm-6 smb-30 xmt-30">
                            <div class="ft__widget">
                                <h2 class="ft__title">Newsletter</h2>
                                <div class="newsletter__form">
                                    <div class="input__box">
                                        <div id="mc_embed_signup">
                                            <form action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                                                <div id="mc_embed_signup_scroll" class="htc__news__inner">
                                                    <div class="news__input">
                                                        <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Email Address" required>
                                                    </div>
                                                    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                                                    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                                                    <div class="clearfix subscribe__btn">
                                                        <input type="submit" value="Send" name="subscribe" id="mc-embedded-subscribe" class="bst__btn btn--white__color">

                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- End Single Footer Widget -->
                        <!-- Start Single Footer Widget -->
                        <div class="col-md-6 col-lg-3 col-sm-6 smt-30 xmt-30">
                            <div class="ft__widget contact__us">
                                <h2 class="ft__title">Contact Us</h2>
                                <div class="footer__inner">
                                    <p> 319 Clematis St. <br> Suite 100 WPB, FL 33401 </p>
                                </div>
                            </div>
                        </div>
                        <!-- End Single Footer Widget -->
                        <!-- Start Single Footer Widget -->
                        <div class="col-md-6 col-lg-2  col-sm-6 smt-30 xmt-30">
                            <div class="ft__widget">
                                <h2 class="ft__title">Follow Us</h2>
                                <ul class="social__icon">
                                    <li><a href="https://twitter.com/devitemsllc" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
                                    <li><a href="https://www.instagram.com/devitems/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
                                    <li><a href="https://www.facebook.com/devitems/?ref=bookmarks" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
                                    <li><a href="https://plus.google.com/" target="_blank"><i class="zmdi zmdi-google-plus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- End Single Footer Widget -->
                    </div>
                </div>
                <!-- Start Copyright Area -->
                <div class="htc__copyright__area">
                    <div class="row">
                        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                            <div class="copyright__inner">
                                <div class="copyright">
                                    <p>© 2022 Uniqlo. Made with <i class="ti-heart"></i> by <a target="_blank" href="https://www.hasthemes.com">HasThemes.</a></p>
                                </div>
                                <ul class="footer__menu">
                                    <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                                    <li><a href="shop.html">Product</a></li>
                                    <li><a asp-action="Contact" asp-controller="Home">Contact Us</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Copyright Area -->
            </div>
        </footer>
        <!-- End Footer Area -->
    </div>
    <script src="~/assets/js/vendor/jquery-3.6.0.min.js"></script>
    <script src="~/assets/js/vendor/jquery-migrate-3.3.2.min.js"></script>
    <script src="~/assets/js/vendor/jquery.waypoints.js"></script>
    <!-- Bootstrap Framework js -->
    <script src="~/assets/js/bootstrap.bundle.min.js"></script>
    <!-- All js plugins included in this file. -->
    <script src="~/assets/js/plugins.js"></script>
    <!-- Main js file that contents all jQuery plugins activation. -->
    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("styles", false)
    @await RenderSectionAsync("scripts", false)
</body>
</html>